# parse the sitecore.json file for the XM Cloud plugin version
[CmdletBinding(DefaultParameterSetName = 'FromArgs')]
param (
    [Parameter(Mandatory)]
    [string]$EnvironmentId
)

$ErrorActionPreference = "Stop"

$XmCloudVersion = (get-content sitecore.json | ConvertFrom-Json).plugins -match 'Sitecore.DevEx.Extensibility.XMCloud' 
if ($XmCloudVersion -eq '' -or $LASTEXITCODE -ne 0) {
    Write-Error "Unable to find version of XM Cloud Plugin"
}
$XmCloudVersion = ($XmCloudVersion -split '@')[1]
$pluginJsonFile = Get-Item -path "$PSScriptRoot\.sitecore\package-cache\nuget\Sitecore.DevEx.Extensibility.XMCloud.$($XmCloudVersion)\plugin\plugin.json"
$XmCloudDeployApi = (Get-Content $pluginJsonFile | ConvertFrom-Json).xmCloudDeployEndpoint #https://xmclouddeploy-api-beta.sitecorecloud.io/
$XmCloudDeployAccessToken = (Get-Content "$PSScriptRoot\.sitecore\user.json" | ConvertFrom-Json).endpoints.xmCloud.accessToken
<#
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im1lZlJoUmEtb3oxczdMU2JRUGFlMCJ9.eyJodHRwczovL2F1dGguc2l0ZWNvcmVjbG91ZC5pby9jbGFpbXMvb3JnX2lkIjoib3JnX1RzN0Exeld0dW9LTEh5NDciLCJodHRwczovL2F1dGguc2l0ZWNvcmVjbG91ZC5pby9jbGFpbXMvb3JnX25hbWUiOiJwZXJmaWNpZW50IiwiaHR0cHM6Ly9hdXRoLnNpdGVjb3JlY2xvdWQuaW8vY2xhaW1zL29yZ19kaXNwbGF5X25hbWUiOiJQZXJmaWNpZW50IiwiaHR0cHM6Ly9hdXRoLnNpdGVjb3JlY2xvdWQuaW8vY2xhaW1zL2VtYWlsIjoiaXZhbi5vbW9yYWNAcGVyZmljaWVudC5jb20iLCJodHRwczovL2F1dGguc2l0ZWNvcmVjbG91ZC5pby9jbGFpbXMvcm9sZXMiOlsiW0dsb2JhbF1cXEV2ZXJ5b25lIiwiW09yZ2FuaXphdGlvbl1cXE9yZ2FuaXphdGlvbiBPd25lciJdLCJodHRwczovL2F1dGguc2l0ZWNvcmVjbG91ZC5pby9jbGFpbXMvY2xpZW50X25hbWUiOiJYTSBDbG91ZCBEZXBsb3kgQ0xJIiwiaXNzIjoiaHR0cHM6Ly9hdXRoLWJldGEuc2l0ZWNvcmVjbG91ZC5pby8iLCJzdWIiOiJhdXRoMHw2MjVlODFlNjUzYjE3YjAwNmZhMGM2OTgiLCJhdWQiOlsiaHR0cHM6Ly9hcGktYmV0YS5zaXRlY29yZWNsb3VkLmlvIiwiaHR0cHM6Ly9vbmUtc2MtYmV0YS5ldS5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjUyNDYzMzk5LCJleHAiOjE2NTI1NDk3OTksImF6cCI6ImNOTkdYR29WRWlLSFpoWVVjWlAzNjU4SFM3UVVHb3I3Iiwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSBvZmZsaW5lX2FjY2VzcyBpZGVudGl0eS51c2VyOnJlYWQgaWRlbnRpdHkudXNlcjp1cGRhdGUgaWRlbnRpdHkudXNlcl9vcmdhbml6YXRpb25zOnJlYWQgYmFja2JvbmUuZXZlbnRzOnJlYWQgaWRlbnRpdHkudXNlcl9yb2xlczpyZWFkIGlkZW50aXR5Lm9yZ2FuaXphdGlvbjpyZWFkIGlkZW50aXR5Lm9yZ2FuaXphdGlvbjp1cGRhdGUgaWRlbnRpdHkub3JnYW5pemF0aW9uX2ludml0YXRpb25zOmxpc3QgaWRlbnRpdHkub3JnYW5pemF0aW9uX2ludml0YXRpb25zOmNyZWF0ZSBpZGVudGl0eS5vcmdhbml6YXRpb25faW52aXRhdGlvbnM6cmVhZCBpZGVudGl0eS5vcmdhbml6YXRpb25faW52aXRhdGlvbnM6ZGVsZXRlIGlkZW50aXR5Lm9yZ2FuaXphdGlvbl9tZW1iZXJzOmxpc3QgaWRlbnRpdHkub3JnYW5pemF0aW9uX21lbWJlcnM6cmVhZCBpZGVudGl0eS5vcmdhbml6YXRpb25fbWVtYmVyczpkZWxldGUgaWRlbnRpdHkub3JnYW5pemF0aW9uX21lbWJlcnNfcm9sZXM6Y3JlYXRlIGlkZW50aXR5Lm9yZ2FuaXphdGlvbl9tZW1iZXJzX3JvbGVzOmRlbGV0ZSBpZGVudGl0eS5yb2xlczpsaXN0IGlkZW50aXR5LnJvbGVzOnJlYWQgeG1jbG91ZGRlcGxveS5wcm9qZWN0czptYW5hZ2UgeG1jbG91ZGRlcGxveS5lbnZpcm9ubWVudHM6bWFuYWdlIHhtY2xvdWRkZXBsb3kuZGVwbG95bWVudHM6bWFuYWdlIHhtY2xvdWRkZXBsb3kubW9uaXRvcmluZy5kZXBsb3ltZW50czpyZWFkIHhtY2xvdWQuY206YWRtaW4geG1jbG91ZC5jbTpsb2dpbiB4bWNsb3VkLmNtOmRlcGxveSBjb25uZWN0LndlYmhvb2tzOnJlYWQgY29ubmVjdC53ZWJob29rczpjcmVhdGUgY29ubmVjdC53ZWJob29rczp1cGRhdGUgY29ubmVjdC53ZWJob29rczpkZWxldGUgcGxhdGZvcm0udGVuYW50czpsaXN0YWxsIGJhY2tib25lLmV2ZW50czplbmFibGUgYmFja2JvbmUuZXZlbnRzOmRpc2FibGUgYmFja2JvbmUuYXVkaXQ6cmVhZCJ9.oDwPO38oHhZZfbmWvxSSsX-t7cSnLy3Chs7dbauls7GTmGMSCp7PRo004OfV5tgTztR7_rACvdFIbUVVM4AIMqYTAWiC8CX2qEPVhrrSGqLQcXN1FYuhny5wT1VE5MslhuDrJU1WUQrpU1dSbaBMMIHsCOQltW48kuc4QLY6v4xzhXKM-XQV77DuYfKq_Z9jKb24RwXdZ-26dbcAn_kKwY25VZ0oIi1wxNFpfd7jS3t7siAXXgfLpuoNzPAHHoIcet_6PoJTD_43IzskCc0lvs2oF8OKU1flYnQdeDQ-mPphDiHjqmzIDo9hfjpF6xWjX2BZCxgoC8vZlD4M3EQ5ww
#>


$Headers = @{"Authorization" = "Bearer $XmCloudDeployAccessToken" }
$URL = @(
    "$($XmCloudDeployApi)api/environments/v1"
    $EnvironmentId
    'obtain-edge-token'
)

$Response = Invoke-RestMethod ($URL -join '/') -Method 'GET' -Headers $Headers -Verbose
$AccessToken = $Response.apiKey
$EdgeUrl = "$($Response.edgeUrl)/api/graphql/ide"
Write-Host "Launching Edge GraphQL IDE"
Write-Host "Add { ""X-GQL-Token"" : ""$AccessToken"" } to the HTTP HEADERS tab at the bottom-left of the screen to write queries against your content"
Start-Process $EdgeUrl
